package org.wangss.Model;

public class SysAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.id
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.authname
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String authname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.authdesc
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String authdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.id
     *
     * @return the value of sys_auth.id
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.id
     *
     * @param id the value for sys_auth.id
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.authname
     *
     * @return the value of sys_auth.authname
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getAuthname() {
        return authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.authname
     *
     * @param authname the value for sys_auth.authname
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setAuthname(String authname) {
        this.authname = authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.authdesc
     *
     * @return the value of sys_auth.authdesc
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getAuthdesc() {
        return authdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.authdesc
     *
     * @param authdesc the value for sys_auth.authdesc
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setAuthdesc(String authdesc) {
        this.authdesc = authdesc;
    }
}