package org.wangss.Model;

public class SysRoleAuthKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.roleid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.authid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String authid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.roleid
     *
     * @return the value of sys_role_auth.roleid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.roleid
     *
     * @param roleid the value for sys_role_auth.roleid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.authid
     *
     * @return the value of sys_role_auth.authid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getAuthid() {
        return authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.authid
     *
     * @param authid the value for sys_role_auth.authid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setAuthid(String authid) {
        this.authid = authid;
    }
}