package org.wangss.Model;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.rolename
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roledesc
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String roledesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.id
     *
     * @return the value of sys_role.id
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.id
     *
     * @param id the value for sys_role.id
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.rolename
     *
     * @return the value of sys_role.rolename
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.rolename
     *
     * @param rolename the value for sys_role.rolename
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roledesc
     *
     * @return the value of sys_role.roledesc
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getRoledesc() {
        return roledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roledesc
     *
     * @param roledesc the value for sys_role.roledesc
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setRoledesc(String roledesc) {
        this.roledesc = roledesc;
    }
}