package org.wangss.Model;

public class SysUserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.userid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.roleid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.userid
     *
     * @return the value of sys_user_role.userid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.userid
     *
     * @param userid the value for sys_user_role.userid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.roleid
     *
     * @return the value of sys_user_role.roleid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.roleid
     *
     * @param roleid the value for sys_user_role.roleid
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }
}