package org.wangss.Model;

public class SysUserRole extends SysUserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.id
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.id
     *
     * @return the value of sys_user_role.id
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.id
     *
     * @param id the value for sys_user_role.id
     *
     * @mbggenerated Sun Jul 16 18:08:29 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }
}